services:
  - type: web
    name: af-novedades
    runtime: python
    buildCommand: "bash build.sh"
    startCommand: "gunicorn servidor_novedades:app --timeout 300 --workers 1"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
